### ISSUE TITLE
Cannot import some models correctly

### ISSUE THREAD

**Issue by rtasan** [dtzxporter/cast#12]
Hello Nick
I tried to import "pilot_heavy_pathfinder_ice_LOD0.cast" by using this addon.
Models and materials were imported correctly but when i try to pose them, this happen.
![image](https://user-images.githubusercontent.com/42664466/119822958-32b4a600-bf2f-11eb-932b-9b2e200bf990.png)

It seems to be failing to apply vertices to vertex_groups
![image](https://i.gyazo.com/f1e5a2663af4c661505407a6070cd6f3.gif)

I also tried maya script and everything worked fine.

**Comment by dtzxporter** [comment]
What version of blender is this, and if you open the blender console, can you paste the error message?

**Comment by rtasan** [comment]
This capture is on Blender 2.92. 
I have tried both 2.90 and 2.80. Neither of them worked correctly.
And there were no error messages in my console. 
This is the Cast file that I want to import. 
https://drive.google.com/drive/folders/1uG-cwjI1tQ5f0moKaoCykQp3HPhiZQ1_?usp=sharing

**Comment by dtzxporter** [comment]
Fixed in latest version of legion afaik.
