### ISSUE TITLE
I get this error whenever trying to import a .CAST file into Blender.

### ISSUE THREAD

**Issue by Kavrrr** [dtzxporter/cast#17]
![image](https://user-images.githubusercontent.com/125680429/219702520-8205f3d4-5072-4cf3-9489-8d1d1cda7456.png)

I am using Blender v3.4.1

**Comment by Legonzaur** [comment]
I got the same problem as you, I fixed it by downloading those two files and replacing them inside the addon directly
`%appdata%\Blender Foundation\Blender\3.5\scripts\addons\io_scene_cast` (you may change the blender version accordingly to yours)

https://github.com/dtzxporter/cast/blob/master/plugins/blender/import_cast.py
https://github.com/dtzxporter/cast/blob/master/plugins/blender/__init__.py

It seems that the repository author forgot to publish a release after fixing it on the repo

**Comment by dtzxporter** [comment]
Oops, this is now fixed.
