### ISSUE TITLE
Cast shows up on top bar, but not in the export formats

### ISSUE THREAD

**Issue by SushiiZ** [dtzxporter/cast#19]
![image](https://github.com/dtzxporter/cast/assets/51277271/564f8acb-dfe6-440a-9373-a6d4b59fcab0)

it shows up in there, but in the export settings (Where I used to export .seanim) it's not there
in my last issue you mentioned to use the ones from the repo itself, that worked for castplugin but there wasn't cast.py in there, so I think it's not working because of that

**Comment by dtzxporter** [comment]
Released latest version.
