### ISSUE TITLE
Support relative single track curves in Maya.

### ISSUE THREAD

**Issue by GhostTF141** [dtzxporter/cast#20]
So I've tried to use some Cast animations in maya and no matter what anim i use it gives me this following error when i try to import it which then doesnt import the anim at all

 `file -import -type "Cast"  -ignoreVersion -ra true -mergeNamespacesOnClash false -namespace "iw9_mp_infil_suv_vehicule_back_crossing"  -pr  -importTimeRange "combine" "F:/download/Cordycep-BE-2.0.0.31/Greyhound/exported_files/modern_warfare_5/xanims/iw9_mp_infil_suv_vehicule_back_crossing.cast";
// Error: line 0: Exception: file E:/Program Files/Autodesk/Maya2018/bin/plug-ins/castplugin.py line 519: Not supported yet: Relative Single Track Curve // 
// File read in  0.007 seconds.
// File read in  0.007 seconds.
// Error: line 0: Error reading file. // `

is this just me or is this something wrong?

**Comment by dtzxporter** [comment]
The plugin doesn't support relative animations at the moment. `Not supported yet: Relative Single Track Curve`

**Comment by dtzxporter** [comment]
@GhostTF141 This should be fixed as of v1.1.1 in Maya. Let me know if this  works for you.

**Comment by dtzxporter** [comment]
Closing unless someone else has an issue.
