### ISSUE TITLE
Unable to enable "cast.py" in maya 2023

### ISSUE THREAD

**Issue by SushiiZ** [dtzxporter/cast#30]
when trying to enable the cast.py I'm getting this error which doesn't let the plugin enable

// Warning: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: No initializePlugin() function
// Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316:  (cast)

the cast import options show up with the top menu, but no export options are visible

**Comment by dtzxporter** [comment]
@SushiiZ You just have to copy both files and only enable `castplugin.py` You should see a cast menu appear and be good to go.

**Comment by dtzxporter** [comment]
Also, there is currently no export support for cast in maya, it is a work-in-progress.

**Comment by SushiiZ** [comment]
ohhh okay that makes a lot more sense, trying to get my animations from maya to blender, used to use .seanim but have been running into some issues and thought cast might've fixed it, but alright, I'll wait on that

**Comment by dtzxporter** [comment]
It should be soon ish, working on feature parity and the spec itself as well.

**Comment by dtzxporter** [comment]
FYI: @SushiiZ Animations can now be exported using File->Export All/Export Selected.
