### ISSUE TITLE
Selecting multiple animations for import only imports last selection | Blender

### ISSUE THREAD

**Issue by ricochhet** [dtzxporter/cast#36]
When importing multiple animations at once it will only import the last animation selected and doesn't attempt to load the others. I have tried with and without the Import Reset option selected, and was not successful. The SEAnim plugin in contrast, does properly import multiple animations.

I am using Blender 4.0.1 with the latest Cast plugin available.

**Comment by dtzxporter** [comment]
Just curious here, when you imported multiple animations, were they all for one armature? Also this seanim plugin? https://github.com/SE2Dev/io_anim_seanim because as far as I'm aware, it only imported one animation at a time.

**Comment by dtzxporter** [comment]
And if you mean import one animation, then import another animation, that would be a different story entirely.

**Comment by ricochhet** [comment]
> Just curious here, when you imported multiple animations, were they all for one armature? Also this seanim plugin? https://github.com/SE2Dev/io_anim_seanim because as far as I'm aware, it only imported one animation at a time.

1. Yes.
2. Yes. The seanim plugin can import multiple animations in a single instance. They will appear in the action editor and can be switched out via the dropdown. They will not appear in the NLA editor.

> And if you mean import one animation, then import another animation, that would be a different story entirely.

I mean selecting multiple animations for one import job.

**Comment by ricochhet** [comment]
Forgive my ignorance, as I'm not super knowledgeable about Blender. SEAnim supports blending animations through the NLA editor, as well as Cast. Unless you meant something else.

Currently, when importing animations one-by-one with Cast, if I have the import reset option toggled it adds a new action and leaves existing actions alone. This is the intended result of what importing multiple animations, to me, should logically be. Where it would add a new action for each imported animation. 

This wouldn't disable blending animations through the NLA, as I can still create a new NLA track, add a couple of actions to the NLA track, and set the in/out blend values of each animation to achieve the desired result.

**Comment by dtzxporter** [comment]
My bad, there is a lot of overlap in the terminology. I was specifically talking about support for blending Additive animation curves, which cast needs to see the existing curve in order to import those properly.

I could make it so import reset allows multiple files to be imported, which would still work for additive curves, because that needs to be disabled in order to import them.

These aren't common, but still good to support.

**Comment by ricochhet** [comment]
I see. Thank you for the clarification! Good luck with your endeavors. :)

**Comment by dtzxporter** [comment]
Supported as of v1.24: https://github.com/dtzxporter/cast/releases/tag/v1.24 with `Import Reset` enabled.
