### ISSUE TITLE
Translation keyframes aren't being applied properly.

### ISSUE THREAD

**Issue by bloodygutsmurphy** [dtzxporter/cast#37]
Animations and mesh normals are completely broken for WaW assets. Tried importing the Nambu and its reload anim, and the clip is offset behind the slot and sticking out of the top of the gun, and the normals were flipped.

Using Blender 3.6 LTS.

**Comment by dtzxporter** [comment]
What produced the cast? Did you convert  from semodel, or export them directly?

**Comment by PavielKraskouski** [comment]
I also have problems with animations in Blender 4.0.1. I'm exporting the Cacodemon model and animations from Doom Eternal using Vega 2.16. The model and animations are in Cast format. No conversions were performed. Here are some frames of the idle animation in Blender and in the game. It is clearly visible that Blender has some problems with the position of the jaw.

![image](https://github.com/dtzxporter/cast/assets/9061796/84844174-76c5-45dc-875a-eaa41b6c7ebe)

![image](https://github.com/dtzxporter/cast/assets/9061796/e32cd1d1-4f38-48ee-a7bd-a73e9dc69c40)

If I import a new animation with "Import resets scene" checked, and then import the idle animation again, the jaw has a different position, but is still incorrect.

![image](https://github.com/dtzxporter/cast/assets/9061796/e196ea2d-7c4d-4c7d-bfa3-3699d1aab1fd)

**Comment by dtzxporter** [comment]
Yes,  it is broken in blender, but not maya:
![image](https://github.com/dtzxporter/cast/assets/22282241/ef08eaa2-d8fa-4373-bd67-972a77c71c27)

**Comment by dtzxporter** [comment]
I will investigate the animation issue separately. @bloodygutsmurphy I am going to create a second issue for the normals specifically, someone else is looking into this for call of duty.

**Comment by dtzxporter** [comment]
Normals: https://github.com/dtzxporter/cast/issues/38

**Comment by dtzxporter** [comment]
@bloodygutsmurphy @PavielKraskouski Please test using v1.23.

**Comment by PavielKraskouski** [comment]
@dtzxporter Cacodemon is fine! Thank you!

![image](https://github.com/dtzxporter/cast/assets/9061796/2954e5e0-08c2-4672-a902-96d3815d04ed)

**Comment by dtzxporter** [comment]
I am going to mark this as solved @bloodygutsmurphy for animations. Translations were broken regardless. If you have an issue using the latest version of the plugin for _animations_ please open a second issue. The normals one remains open.

**Comment by bloodygutsmurphy** [comment]
What do you mean translations were broken regardless?
