### ISSUE TITLE
A few cast bugs

### ISSUE THREAD

**Issue by Black-DeathZM** [dtzxporter/cast#4]
Unsure if you're aware of these, but figured I might as well help a bit if possible by pointing out issues I find;

Issue 1: [For this issue, the rig in use is Thomas Cat's Apex-T7 rig, but I checked a ptpov base rig & it had the same issue] hand movement in animation. Weapon is the Wingman, animation is fire_0 played on ads_in/out used as a base. Expected movement would be something like this https://gyazo.com/aef2e7f4d1e621fc8ad30da5ebe5d861 (on SEAnim), whereas on cast the left arm moves weirdly https://gyazo.com/edcc1e90e98a66d13797d01852a10dec

Issue 2: It seems like after importing a cast animation [and another at a scene time], resetting the scene and/or reloading the scene then importing another cast animation with scene time off - the arms do not behave as expected, and go off to sides. (e.g. importing ads_in after a scene reload https://gyazo.com/86fbc3294a8e7ca4abb2d1227ada5304)

I imagine you probably know about these issues already, but in case you don't, I thought I'd submit them. Nevertheless, the cast format seems really promising and I'm looking forward to using the finished product, it's definitely going to make things a lot simpler.

Edit: In case Maya version matters, I'm running 2017.

**Comment by dtzxporter** [comment]
The scene reload issue I am aware of, working on it.

For fire_0 are you importing it to the **end** of ads_in? Using the setting in the dropdown?

(Cast blend at frame 0 otherwise)

I need to verify this on the stock rig first, before comparing to a conversion rig.

**Comment by Black-DeathZM** [comment]
Yeah, can confirm that I'm importing the fire_0 animation at the end of ads_in, with Import at Scene Time enabled

**Comment by dtzxporter** [comment]
Also I just checked the code from SETools, I never included the additive translations, which may account for the differences you see. I only "added" the rotations, which is the wrong logic. Cast applies the translations/rotations

**Comment by dtzxporter** [comment]
https://github.com/dtzxporter/SETools/blob/master/SEToolsPlugin.py#L1489 for reference

**Comment by Black-DeathZM** [comment]
Ah right, the process I've been using is to use an anim layer to apply the additive SEAnim anim at the end of a non-additive SEAnim (though right now I'm having some technical difficulties in producing it through this process right now..) - whether or not that's correct, it does however seem as if from in-game firing that the Wingman doesn't have the left hand rightward translation that occurs with the cast animation (In-game: https://youtu.be/to2r_4sKd2c, vs with cast: https://gyazo.com/75d9efc80e02872daadf6c7d12515dfc)

**Comment by dtzxporter** [comment]
I am going to inspect the frame to see exactly what the value should be. The new Legion update also changed the data in the animation for additive ones (Including seanims) they should also have changed post update. So there is likely a discrepancy here.

**Comment by dtzxporter** [comment]
Newest release fixes this issue!

**Comment by Black-DeathZM** [comment]
Great, thanks man!
