### ISSUE TITLE
Addon doesn't install properly in blender on macOS/Linux due to backslash in the zip file.

### ISSUE THREAD

**Issue by PavielKraskouski** [dtzxporter/cast#40]
When I try to import a model into Blender, it throws an error:

![](https://github.com/dtzxporter/cast/assets/9061796/e690dbc0-e88d-485e-96fc-69c8e013806b)

Here you can see how the addon is installed in a folder with other addons:

![](https://github.com/dtzxporter/cast/assets/9061796/55b95aa7-b87c-4195-8416-d26fc5d6bba8)

I think the problem is an incorrect backslash in the addon path:

![Screenshot from 2023-11-29 02-32-54](https://github.com/dtzxporter/cast/assets/9061796/f8adcab0-7604-467a-ad2b-d85c683cf72c)

**Comment by dtzxporter** [comment]
This is an issue with the installer I believe, blender 4.0 seems to have broken paths. It's supposed to make folders. I'm not sure why it stopped working in 4.0, it's possible that they didn't normalize the paths.

**Comment by dtzxporter** [comment]
[blender_cast_plugin.zip](https://github.com/dtzxporter/cast/files/13494583/blender_cast_plugin.zip)
Please try with this zip.

**Comment by dtzxporter** [comment]
Ok, I will do this from now on.
