### ISSUE TITLE
Animations Still Broken with Latest Version.

### ISSUE THREAD

**Issue by bloodygutsmurphy** [dtzxporter/cast#41]
Same problem as last time. Translations are completely fucked. Just imported the Nambu and the "pullout" animation, and the clip and bolt are offset outside of the weapon.

**Comment by dtzxporter** [comment]
Can you post a screenshot and upload a sample model and animation that replicates the issue? I will investigate this issue.

**Comment by dtzxporter** [comment]
Please re-open if you have more information.
