### ISSUE TITLE
Scale keyframes import incorrectly because they are based on rest position.

### ISSUE THREAD

**Issue by PavielKraskouski** [dtzxporter/cast#46]
After importing the animation shown in #42 (`pose_slayer_standing_blade_extending`), I noticed an inaccuracy in the positioning of the blade relative to the hand. In Blender, the blade intersects with the hand. In the game you can see that there is no intersection.

![image](https://github.com/dtzxporter/cast/assets/9061796/bedfb46f-b748-44c2-9fe6-432aaea7b124)

![00001](https://github.com/dtzxporter/cast/assets/9061796/286437bb-6762-47a3-9b6d-6e896e6e83e0)

**Comment by dtzxporter** [comment]
Assuming you mean `pose_slayer_standing_blade_extended`?

**Comment by PavielKraskouski** [comment]
This is the name of the animation I exported from Doom Eternal using Vega. The full path to the animation is the following: `md6/characters/humans/doomslayer/base/motion/photo_mode/pose_slayer_standing_blade_extended`. Here is a screenshot of this animation from Blender (it's actually a pose, not an animation):

![image](https://github.com/dtzxporter/cast/assets/9061796/0a80521e-5513-42b7-b59f-3f0f513edf46)

After carefully examining the pose, I noticed that there is a difference between Blender and the game in the position of the knife relative to the hand.

**Comment by dtzxporter** [comment]
Yes, you had a typo in the first post.

**Comment by dtzxporter** [comment]
It's related to scale keyframes, the knife is actually correct, it's his knuckles that are incorrectly scaled.

**Comment by PavielKraskouski** [comment]
Yeah, just realized I made a typo in the name of the animation.

**Comment by dtzxporter** [comment]
This issue is fixed as of plugin version 1.31. You'll need to re-import the model as well in order for it to import correctly.
