### ISSUE TITLE
No effect when importing animations by console

### ISSUE THREAD

**Issue by DTMination** [dtzxporter/cast#55]
`bpy.ops.import_scene.cast(filepath="M:\\xxx\\xxx.cast")`
When typing this in console, it returns " Cast has been loaded {'FINISHED'}", however the model still in T-Pose and no animation has loaded. AMATURE has been selected.
![image](https://github.com/dtzxporter/cast/assets/62316089/5706b165-2e24-428b-abf9-6dc478e1a21c)

**Comment by dtzxporter** [comment]
And this animation works when importing with the file dialog?

**Comment by DTMination** [comment]
> And this animation works when importing with the file dialog?这个动画在导入文件对话框时有效吗？

Yes. Manual import through the dialog is OK and animations can be imported.
