### ISSUE TITLE
Importing animations results in odd location values for moving parts

### ISSUE THREAD

**Issue by PalindroneV2** [dtzxporter/cast#58]
Importing animations results in odd offset values for magazines/bolts/other moving parts

AUG files imported from Black Ops 1 using Greyhound
![image](https://github.com/dtzxporter/cast/assets/7397535/06589589-da08-4b7b-970c-d3c3ae219ca8)

**Comment by dtzxporter** [comment]
cc @echo000 and @dest1yo

**Comment by PalindroneV2** [comment]
I should ask, is this issue at all new? Should I go back and test on another version of blender/another build of CAST?
Currently I've got Blender 4.1 (latest on steam) and CAST 1.40 so I've got no clue if this specific combination is broken and another builld/verion is totally fine.

I've been able to get around the issue with the weird offsets by using the graph editor to move around the keyframes but i've hit walls like the shells for this BO1 Python where the totally netural pose has them completely discarded but the idle needs them offset inside the cylinder.

Neutral
![image](https://github.com/dtzxporter/cast/assets/7397535/0a599c14-8d5e-4a3d-ab68-c3a8c93906d6)
Imported idle animation with no changes (hid the meshes for other gun parts for visibility)
![image](https://github.com/dtzxporter/cast/assets/7397535/19760428-d276-47f4-9f71-571415b28ca4)

**Comment by dtzxporter** [comment]
One of the things about cod specifically is that no one is dedicated to working on it anymore, there are certain cod features that cast has, that are necessary for certain animations.

Cast is tested by myself against games I'm actively involved with.

**Comment by dtzxporter** [comment]
The fix for Greyhound is pending, I'm going to close this issue, if you have any new problems please create a new issue.
