### ISSUE TITLE
Importing animations into Maya gives different results compared to Blender

### ISSUE THREAD

**Issue by joecons97** [dtzxporter/cast#59]
Hello,

I have recently been playing around with import .cast models/animations from MW2 (2022) into both blender and maya. 
Yesterday I was trying to build the animation set for the M4 and noticed that the "j_gun" bone imports different in maya compared to blender.

Looking at the positions, blender seems to be correct and maya seems to be wrong. Please see images below:
**Maya**
![image](https://github.com/dtzxporter/cast/assets/10887047/0c271bd0-2f8f-4f14-86e3-620a0829daa8)

**Blender**
![image](https://github.com/dtzxporter/cast/assets/10887047/e4ca60c3-cbd6-4e48-acad-eec92b7ccfb4)

**Comment by dtzxporter** [comment]
This looks like the opposite bug actually, I believe the cast file is incorrectly marking the j_gun as relative, and blender isn't respecting that.

I'll have @echo000 and @dest1yo look into it.

**Comment by joecons97** [comment]
One other quick thing that I just noticed:
There is some funkiness going on with the pinky finger in Maya too.
![image](https://github.com/dtzxporter/cast/assets/10887047/ca8c7ffb-8ac1-4195-8957-54371e7cbb2d)

**Comment by dtzxporter** [comment]
Can you upload a cast arm + animation sample that produced the above image? No need for the weapon for now.

**Comment by joecons97** [comment]
[requested_cast_files.zip](https://github.com/dtzxporter/cast/files/14811425/requested_cast_files.zip)

@dtzxporter Please find attached - I did find that with the most recent build of the cast tools (in maya) the first import is the same as blender, but when I did "new scene" and then imported all of the bits again, then it was different.
