### ISSUE TITLE
Cinema 4D importer

### ISSUE THREAD

**Issue by Devostated** [dtzxporter/cast#6]
Hello Porter,
a Cinema 4D importer might not be a big thing for modders, but for people who do rendering.
Us moviemakers, thumbnail artists etc. mostly work Cinema 4D, while Blender is just some tool to do import export. 
We could use FBX format and export from Maya or Blender, but FBX gives us many problems. Such as: 
Maya
https://gyazo.com/d1b935198e1349d2a10a279ca3238672
C4D 
https://gyazo.com/3c5a4e8aadcc869d76874f8bdc3eaea7

A support for the Cast format would solve such problems, since there is also no seanim plugin and would come in handy for other tools such as Greyhound or C2M that are planning to add/use the cast file format.

**Comment by dtzxporter** [comment]
I'm going to close this as not-planned at the moment unless someone wants to step up and write one.
