### ISSUE TITLE
Sometimes Maya Export doesn't work

### ISSUE THREAD

**Issue by SushiiZ** [dtzxporter/cast#62]
Sometimes I get this error when exporting my animation, this happened with the .seanim plugin too (mainly when using animation layers) but I'm getting it with cast too, this time with no animation layers

`cast.py line 142: ubyte format requires 0 <= number <= 255`

no idea what this means or how I fix it, only way I could export previously was with external plugins and copying and pasting the animation and then rebaking it, and that would only fix it sometimes, no clue what's causing this

**Comment by dtzxporter** [comment]
Is there any chance you can provide a scene that produces this problem?

**Comment by dtzxporter** [comment]
This is because there is a keyframe @ -1. Cast only supports >= 0. I can update the plugin to force it to start at 0 if that would make more sense?

**Comment by dtzxporter** [comment]
![maya_43d2ohAQQU](https://github.com/dtzxporter/cast/assets/22282241/1310a98f-d54b-4655-8891-f2a47530c7f7)
Here
