### ISSUE TITLE
'bpy_prop_collection[key]: key "Ambient Occlusion" not found'

### ISSUE THREAD

**Issue by gnisbet** [dtzxporter/cast#65]
When attempting to import meshes I get the above issue. It also occurs when importing meshes in a loop using:

`bpy.ops.import_scene.cast(filepath = model_filepath)`

However, when I use this on a mesh outside the loop it seems to work fine, any ideas?

**Comment by dtzxporter** [comment]
Blender version?

**Comment by gnisbet** [comment]
Sorry, 4.2.0. The latest LTS release.

Thanks for getting back so quickly!

**Comment by dtzxporter** [comment]
Fixed in v1.59.
