### ISSUE TITLE
World at War human animations have strange root motion when imported

### ISSUE THREAD

**Issue by SmartDonkey0000** [dtzxporter/cast#66]
Hello, I noticed there's a strange issue regarding the root bone's movement in Blender when importing human animations from World at War. It looks strange in Cast but the older Seanim plugin doesn't seem to have this issue. There is a buildup to its speed and then slows down as the animation ends.

Cast:

https://github.com/user-attachments/assets/bba50859-72c6-4364-ad9d-6ce655f56ad9

Seanim:

https://github.com/user-attachments/assets/fe439931-9de5-4171-8972-850c2fdfc507

There is also one more issue I want to address; it seems that the Import Resets Scene option is no longer working, resulting in the next animation import causing the model to appear strange. This was tested on the latest version of Cast (1.59) and Blender 3.3

**Comment by dtzxporter** [comment]
You'll have to provide samples (the model, the seanim, and the cast file in order for me to debug the issue). Otherwise you'll have to wait for someone that work on cod to investigate.

**Comment by SmartDonkey0000** [comment]
Here are the samples: https://mega.nz/file/9D9SEAhJ#tZjNkqzqoyp9hginM81DHEhkTkCIvggNh6FbIiwvaEQ

**Comment by dtzxporter** [comment]
Fixed in v1.60.

**Comment by dtzxporter** [comment]
v1.61 fixes import reset scene as well.

**Comment by SmartDonkey0000** [comment]
I just tested it out and it works, thank you!
