### ISSUE TITLE
Add support for multiple vertex colors

### ISSUE THREAD

**Issue by wannkunstbeikor** [dtzxporter/cast#67]
Im trying to implement an exporter from Frostbite meshes to cast and they use multiple vertex colors and also store some other stuff that i packed into vertex colors with fbx. And from what i saw Cast only supports 1 vertex colors, would it be possible to update it, so it could support multiple vertex colors?

**Comment by dtzxporter** [comment]
Yes, this will just take me a little to verify that the new spec will be backwards compatible with cast files written previously, but it shouldn't be too hard.

**Comment by wannkunstbeikor** [comment]
Also another question, can you set the coordinate system which is used in cast. Frostbite is using a Y up coordinate system, so when I import the cast in blender its not correct. Do I need to convert the vertices when creating the cast file or can I set an option so it imports correctly?
![image](https://github.com/user-attachments/assets/5977d389-48cb-42f3-817f-e9894a71f1fd)

**Comment by dtzxporter** [comment]
I've debated this in the past, the main issue is I don't want to modify the data when you import files, other software like Maya, C4d lets you change the axis on the fly. This gets into issues with animations. Still thinking about it, but for now if you want to modify the data you export that's ok too.

**Comment by wannkunstbeikor** [comment]
Okay thanks, that looks good, I also would rather avoid modifying the vertex data myself.
