### ISSUE TITLE
Import in Script Support for Blender?

### ISSUE THREAD

**Issue by wojo81** [dtzxporter/cast#69]
Could there please be support for importing in scripts in Blender, or if there already is, provide some examples somewhere. I have spent the past two days getting nothing done on my project, trying to mess with the import_cast.py file.

**Comment by dtzxporter** [comment]
Its always been possible, see: https://github.com/llennoco22/Apex-mprt-importer-for-Blender/blob/main/ApexMapImporter/panel_op.py#L80

**Comment by dtzxporter** [comment]
Let me know if this is what you mean, otherwise I need more info.

**Comment by dtzxporter** [comment]
I'm going to close this issue and assume you got it working. Please open a new issue if you still have problems / want to make a request.
