### ISSUE TITLE
FaceBuffer indices

### ISSUE THREAD

**Issue by sheilan102** [dtzxporter/cast#8]
Are the indices of a FaceBuffer relative to the mesh, so 1/2/3 would mean first 3 vertices of current mesh, or are they pointing to a main pool of vertices like Wavenfront OBJ?

**Comment by dtzxporter** [comment]
Face buffer indices are per mesh, so 0, 1, 2 == first 3 vertices.

**Comment by dtzxporter** [comment]
Clarified in footnote of mesh.
