### ISSUE TITLE
 ProjectD3code

### ISSUE THREAD

**Issue by saeid0034** [dtzxporter/cast#9]
IM REALLY SORRY for asking this Question here
there is anyway to get  ProjectD3code project working with Call of Duty: Modern Warfare 2 Campaign Remastered
(this game support this type of text inject like CD OL?)

**Comment by dtzxporter** [comment]
Invalid, ProjectD3code is discontinued and would have to be completely rewritten to support a new title. CodOL is based on mw2 (2009).
